### ISSUE TITLE
Error Downloading Full Mail (Russian)

### ISSUE THREAD

**Issue by Naghual** [openlabs/poweremail#13]
When pressing 'Download Full Mail' button, error appears:

web-services:Uncaught exception
Traceback (most recent call last):
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/osv/osv.py", line 122, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/osv/osv.py", line 176, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/osv/osv.py", line 167, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/openlabs-poweremail-652f768/poweremail_mailbox.py", line 157, in complete_mail
    self.pool.get('poweremail.core_accounts').get_fullmail(cr, uid, id, context)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/openlabs-poweremail-652f768/poweremail_core.py", line 1007, in get_fullmail
    server_ref, mailid, context)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/openlabs-poweremail-652f768/poweremail_core.py", line 734, in complete_mail
    self.save_attachments(cr, uid, mail, mailboxref, parsed_mail, coreaccountid, context)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/openlabs-poweremail-652f768/poweremail_core.py", line 749, in save_attachments
    'description':(self.decode_header_text(mail['subject']) or _('No Subject')) + " [Type:" + (each[0] or 'Unknown') + ", Filename:" + (each[1] or 'No Name') + "]",
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 5: ordinal not in range(128)

> /opt/openerp/lib/python2.7/site-packages/openerp-server/addons/openlabs-poweremail-652f768/poweremail_core.py(749)save_attachments()
> -> 'description':(self.decode_header_text(mail['subject']) or _('No Subject')) + " [Type:" + (each[0] or 'Unknown') + ", Filename:" + (each[1] or 'No Name') + "]",

some investigation:

(Pdb) l
744             for each in parsed_mail['attachments']:#Get each attachment
745                 new_att_vals = {
746                             'name':self.decode_header_text(mail['subject']) + '(' + each[0] + ')',
747                             'datas':base64.b64encode(each[2] or ''),
748                             'datas_fname':each[1],
749  ->                         'description':(self.decode_header_text(mail['subject']) or _('No Subject')) + " [Type:" + (each[0] or 'Unknown') + ", Filename:" + (each[1] or 'No Name') + "]",
750                             'res_model':'poweremail.mailbox',
751                             'res_id':id
752                                 }
753                 att_ids.append(att_obj.create(cr, uid, new_att_vals, context))
754                 logger.notifyChannel(_("Power Email"), netsvc.LOG_INFO, _("Downloaded & saved %s attachments Account: %s.") % (len(att_ids), coreaccountid))
(Pdb) self.decode_header_text(mail['subject'])
'Fwd: \xd0\x9e\xd1\x82\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0: \xd0\xa1\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x8f\xd0\xbd\xd0\xb8\xd0\xb5_\n \xd0\xb3\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd0\xb8_\xd0\x98\xd0\x93\xd0\x9f_23122011.xls'
(Pdb) mail['subject']
'Fwd: =?UTF-8?B?0J7RgtC/0YDQsNCy0LrQsDog0KHQvtGB0YLQvtGP0L3QuNC1Xw==?=\n =?UTF-8?B?0LPQvtGC0L7QstC90L7RgdGC0Lhf0JjQk9CfXzIzMTIyMDExLnhscw==?='
(Pdb)

**Comment by sharoonthomas** [comment]
Can you try with the dev branch and report if you still facing the issue ?

https://github.com/openlabs/poweremail/tree/dev

**Comment by Naghual** [comment]
This issue currently occurs at that release. Sorry that i forget to point it from the begining.

**Comment by sharoonthomas** [comment]
Hi Naghual,

You are still using the older version, because your stack trace points to `poweremail_core.py` while the new versions don't have the file :)

To download the new version goto https://nodeload.github.com/openlabs/poweremail/zipball/dev and extract the folder replacing your current poweremail module directory.

**Comment by Naghual** [comment]
Well, yes. My mistake.
I get rid of old version.

Installing a new one I'm getting this:

[2011-12-22 12:08:41,863][openerp] INFO:init:module openlabs-poweremail-8edb1dc: loading objects
[2011-12-22 12:08:41,863][openerp] INFO:init:module openlabs-poweremail-8edb1dc: registering objects
[2011-12-22 12:08:41,863][openerp] CRITICAL:init:Couldn't load zip module openlabs-poweremail-8edb1dc
[2011-12-22 12:08:41,863][openerp] CRITICAL:init:not a Zip file: '/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/openlabs-poweremail-8edb1dc.zip'
[2011-12-22 12:08:41,864][openerp] ERROR:web-services:Uncaught exception
Traceback (most recent call last):
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/osv/osv.py", line 122, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/osv/osv.py", line 176, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/osv/osv.py", line 167, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/base/module/wizard/base_module_upgrade.py", line 98, in upgrade_module
    _db, pool = pooler.restart_pool(cr.dbname, update_module=True)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/pooler.py", line 60, in restart_pool
    return get_db_and_pool(db_name, force_demo, status, update_module=update_module)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/pooler.py", line 39, in get_db_and_pool
    addons.load_modules(db, force_demo, status, update_module)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/__init__.py", line 883, in load_modules
    processed_modules.extend(load_module_graph(cr, graph, status, report=report, skip_modules=processed_modules))
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/**init**.py", line 716, in load_module_graph
    register_class(package.name)
  File "/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/**init**.py", line 455, in register_class
    zimp = zipimport.zipimporter(zip_mod_path)
ZipImportError: not a Zip file: '/opt/openerp/lib/python2.7/site-packages/openerp-server/addons/openlabs-poweremail-8edb1dc.zip'

> /opt/openerp/lib/python2.7/site-packages/openerp-server/addons/**init**.py(455)register_class()
> -> zimp = zipimport.zipimporter(zip_mod_path)
