### ISSUE TITLE
Unable to install on OERP 6.1

### ISSUE THREAD

**Issue by jarodthomas** [openlabs/poweremail#29]
Hi, while trying to install poweremail 6.1.0.7 on OERP 6.1 I receive following error messages :

Client Traceback (most recent call last):
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\common\http.py", line 180, in dispatch
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\controllers\main.py", line 1052, in call_button
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\controllers\main.py", line 996, in call_common
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\controllers\main.py", line 1010, in _call_kw
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\common\openerplib\main.py", line 250, in proxy
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\common\openerplib\main.py", line 117, in proxy
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\common\http.py", line 608, in send

Server Traceback (most recent call last):
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\web\common\http.py", line 593, in send
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\netsvc.py", line 360, in dispatch_rpc
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\service\web_services.py", line 586, in dispatch
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\osv\osv.py", line 167, in execute_kw
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\osv\osv.py", line 121, in wrapper
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\osv\osv.py", line 176, in execute
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\osv\osv.py", line 164, in execute_cr
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server\openerp\addons\base\module\wizard\base_module_upgrade.py", line 101, in upgrade_module
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\pooler.py", line 39, in restart_pool
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\modules\registry.py", line 202, in new
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\modules\loading.py", line 338, in load_modules
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\modules\loading.py", line 253, in load_marked_modules
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\modules\loading.py", line 192, in load_module_graph
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\modules\loading.py", line 90, in <lambda>
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\modules\loading.py", line 132, in _load_data
  File "C:\Program Files\OpenERP6.1-20120923-233042\Server\server.\openerp\tools\convert.py", line 970, in convert_csv_import
AttributeError: 'NoneType' object has no attribute 'import_data'

Can you please help?

Thanks,
JT

**Comment by fuxp** [comment]
Exactly the same error on 6.1 checked with the latest version of OpenERP and Powermail - any sugestions?

**Comment by sharoonthomas** [comment]
@fuxp are you also on windows ?

**Comment by fuxp** [comment]
No -  ubuntu 12.4

**Comment by jarodthomas** [comment]
Forgot to mention : WinXP SP3 ... sorry

Greetz,
JT

**Comment by sharoonthomas** [comment]
Looks like its not an OS dependent issue since both your OSs are different. Can you confirm the branch that is installed ? is it the dev branch ?

**Comment by fuxp** [comment]
I tooked this one: lp:~credativ/poweremail/poweremail-6.1

**Comment by sharoonthomas** [comment]
We dont maintain the project anymore on launchpad. It is maintained here on github.
Can you try with the github code ?

**Comment by fuxp** [comment]
Just tried it with the latest version ( zip) from here - same result...same error

**Comment by jarodthomas** [comment]
Hey Sharoon, I pulled the dev branch from here (https://github.com/openlabs/poweremail -> zip button)

**Comment by jarodthomas** [comment]
oops, wrong button

**Comment by sharoonthomas** [comment]
It could be a zip import issue. Why don't you try extracting the module code into a folder and then putting the folder in the addons path ?

**Comment by jarodthomas** [comment]
OK, will try that later on, for now the system is importing data from Magento (I understood you were also involved in that Magento2OERP project, congrats for the good work), will keep you posted. Thanks, JT.

**Comment by jarodthomas** [comment]
Hi there,

It is a zip import issue as you suspected, I pulled the module through git (git://github.com/openlabs/poweremail.git), and presto : it installed right away.

Thanks for your precious help,
JT.
